# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd7945260644a7f997da3d7906609887886a0e65215a3e16c84ac137fc5aaaac3cbc3deb9a39c2ecfdbfc6cd3ab0e4dbef94f9defccbadf0ae52b62f0fbaf110

test:
  secret_key_base: 8af93175d6566807c255596f56b7ad7517d6275f0c95ea07c1b12e3e8c7adbd1a71693c9e629c9cba5a2b982fa393bdf97eb24bc39bd65b3b24f0007d489222e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
